
CREATE USER tododb_user WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD '1237';




--DROP DATABASE tododb
CREATE DATABASE tododb
    WITH 
    OWNER = tododb_user;
	
CREATE TABLE tasks(
    id SERIAL PRIMARY KEY,
    task VARCHAR NOT NULL

);


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO tododb_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO tododb_user;